name: CI - project 7

on:
  push:
    paths: ['project 7/**']
  pull_request:
    paths: ['project 7/**']
  workflow_dispatch: {}

jobs:
  # TODO: Add build and test jobs
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "CI for project 7 - to be implemented"
