name: CI - project 6

on:
  push:
    paths: ['project 6/**']
  pull_request:
    paths: ['project 6/**']
  workflow_dispatch: {}

jobs:
  # TODO: Add build and test jobs
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "CI for project 6 - to be implemented"
