name: CI - project 4

on:
  push:
    paths: ['project 4/**']
  pull_request:
    paths: ['project 4/**']
  workflow_dispatch: {}

jobs:
  # TODO: Add build and test jobs
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "CI for project 4 - to be implemented"
